tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.index, name="index"),
    path("list/", views.TaskListView.as_view(), name="list"),
    path("list/c/<slug:cat_slug>", views.tasks_by_cat, name="list_by_cat"),
    path("details/<int:pk>", views.TaskDetailsView.as_view(), name="details"),
    path("time", views.timer, name="timer"),
]

todoapp/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('tasks.urls', namespace="tasks")),
    path('admin/', admin.site.urls),
]

if not settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls))
    ] + urlpatterns

tasks/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Category(models.Model):
    slug = models.CharField(max_length=128)
    name = models.CharField(max_length=256)
    todos_count = models.PositiveIntegerField(default=0)
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return f'{self.name} ({self.slug})'


class TodoItem(models.Model):
    PRIORITY_HIGH = 1
    PRIORITY_MEDIUM = 2
    PRIORITY_LOW = 3

    PRIORITY_CHOICES = [
        (PRIORITY_HIGH, "Высокий приоритет"),
        (PRIORITY_MEDIUM, "Средний приоритет"),
        (PRIORITY_LOW, "Низкий приоритет"),
    ]

    description = models.TextField("описание")
    is_completed = models.BooleanField("выполнено", default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="tasks"
    )
    priority = models.IntegerField(
        "Приоритет", choices=PRIORITY_CHOICES, default=PRIORITY_MEDIUM
    )
    category = models.ManyToManyField(Category, blank=True)

    def __str__(self):
        return self.description.lower()

    def get_absolute_url(self):
        return reverse("tasks:details", args=[self.pk])

tasks/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from tasks.models import TodoItem, Category
from django.core.cache import cache
import time
from django.shortcuts import render
from django.http import HttpResponse
from datetime import datetime
from django.template import loader
from django.views.decorators.cache import cache_page

@cache_page(300)
def timer(request):
    
    context = datetime.now()
    cache.get('some_key')
    cache.set('some_key', context)
    cache.get('some_key')
    return HttpResponse(cache.get('some_key'))


def index(request):

    # 1st version
    # counts = {t.name: random.randint(1, 100) for t in Tag.objects.all()}

    # 2nd version
    # counts = {t.name: t.taggit_taggeditem_items.count()
    # for t in Tag.objects.all()}

    # 3rd version
    from django.db.models import Count

    counts = Category.objects.all()

    return render(request, "tasks/index.html", {"counts": counts})


def filter_tasks(tags_by_task):
    return set(sum(tags_by_task, []))


def tasks_by_cat(request, cat_slug=None):
    u = request.user
    tasks = TodoItem.objects.filter(owner=u).all()

    cat = None
    if cat_slug:
        cat = get_object_or_404(Category, slug=cat_slug)
        tasks = tasks.filter(category__in=[cat])

    categories = []
    for t in tasks:
        for cat in t.category.all():
            if cat not in categories:
                categories.append(cat)

    return render(
        request,
        "tasks/list_by_cat.html",
        {"category": cat, "tasks": tasks, "categories": categories},
    )


class TaskListView(ListView):
    model = TodoItem
    context_object_name = "tasks"
    template_name = "tasks/list.html"

    def get_queryset(self):
        u = self.request.user
        qs = super().get_queryset()
        return qs.filter(owner=u)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_tasks = self.get_queryset()
        tags = []
        for t in user_tasks:
            tags.append(list(t.category.all()))

        categories = []
        for cat in t.category.all():
            if cat not in categories:
                categories.append(cat)
        context["categories"] = categories

        return context


class TaskDetailsView(DetailView):
    model = TodoItem
    template_name = "tasks/details.html"

tasks/templates/tasks/details.html
{% extends "base.html" %}
{% block title %}Задача {{ object.id }}{% endblock %}

{% block main_content %}
  <h1>Задача</h1>
  <p><b>Описание</b>: {{ object }}</p>
  <ul>
    <li>
      {{ object.is_completed|yesno:"Выполнена,Не выполнена" }}
    </li>
    <li><i class="far fa-calendar-alt"></i>&nbsp;Создана: {{ object.created|date:"Y-b-d H:i" }}</li>
    <li><i class="far fa-clock"></i>&nbsp;Последнее изменение: {{ object.updated }}</li>
  </ul>
  <i class="fas fa-clipboard-list"></i>&nbsp;<a href="{% url "tasks:list" %}">Назад к списку</a>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "base.html" %}
{% load static %}
{% load cache %}

{% block title %}Информация по категориям{% endblock %}

{% block main_content %}
  <h1>Категории и числа</h1>
  <ul>
  {% for cat in counts %}
    <li><span class="badge badge-info">{{ cat.name }}: {{ cat.todos_count }} </span></li>
  {% empty %}
    <li>Список задач по категориям пуст. Попробуйте добавить их из админки</li>
  {% endfor %}
  </ul>

{% endblock %}

tasks/templates/tasks/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Задачи{% endblock %}

{% block main_content %}
  <h1>Текущие задачи</h1>
    <ul class="list-inline">
    {% for cat in categories %}
      <li class="list-inline-item">
        <span class="badge badge-info">{{ cat.name }}</span>
      </li>
    {% endfor %}
    </ul>
  <ul id="todo-list">
  {% for task in tasks %}
    {% if task.is_completed %}
    <li class="completed">
      <input class='checkbox' data-uid={{ task.id }} type='checkbox' disabled='disabled' checked='checked'/>
    {% endif %}
    {% if task.priority == task.PRIORITY_HIGH %}
      <span class="badge badge-pill badge-danger">&nbsp;</span>
    {% elif task.priority == task.PRIORITY_MEDIUM %}
      <span class="badge badge-pill badge-secondary">&nbsp;</span>
    {% elif task.priority == task.PRIORITY_LOW %}
      <span class="badge badge-pill badge-success">&nbsp;</span>
    {% endif %}
      <a href={% url "tasks:details" task.id %}>{{ task.description }}</a>
      <hr/>
    </li>
  {% endfor %}
  </ul>
{% endblock %}

tasks/templates/tasks/list_by_cat.html
{% extends "base.html" %}
{% load static %}

{% block title %}Задачи на день{% endblock %}

{% block main_content %}
  {% if category %}
  <h1>Задачи категории "{{ category.name }}"</h1>
  {% else %}
  <h1>Все текущие задачи</h1>
  {% endif %}
    {% for t in categories %}
      {% if forloop.first %}
      <ul class="list-inline">
        <li class="list-inline-item">Все категории:</li>
      {% endif %}
      <li class="list-inline-item">
        <a href="{% url "tasks:list_by_cat" t.slug %}">
        {% if t.pk == tag.pk %}
          <span class="badge badge-success">{{ t.name }}</span>
        {% else %}
          <span class="badge badge-info">{{ t.name }}</span>
        {% endif %}
        </a>
      </li>
    {% if forloop.last %}</ul>{% endif %}
    {% endfor %}
  <hr/>

  <ul id="todo-list">
  {% for task in tasks %}
    {% if task.is_completed %}
    <li class="completed">
      <input class='checkbox' data-uid={{ task.id }} type='checkbox' disabled='disabled' checked='checked'/>
    {% endif %}
      {% if task.priority == task.PRIORITY_HIGH %}
      <span class="badge badge-pill badge-danger">&nbsp;</span>
      {% elif task.priority == task.PRIORITY_MEDIUM %}
      <span class="badge badge-pill badge-secondary">&nbsp;</span>
      {% elif task.priority == task.PRIORITY_LOW %}
      <span class="badge badge-pill badge-success">&nbsp;</span>
      {% endif %}
      <a href={% url "tasks:details" task.id %}>{{ task }}</a>
      <hr/>
    </li>
  {% endfor %}
  </ul>
{% endblock %}

tasks/templates/tasks/time.html
{% extends "base.html" %}
{% load static %}

{% block title %}Информация по таймеру{% endblock %}

{% block main_content %}
  <h1>Категории и числа</h1>
  <ul>
    <li><span class="badge badge-info">{{ context }}</span></li>

{% endblock %}

templates/base.html
<html>
  <head>
    <title>{% block title %}PWS Todo example app{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <script src="http://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    {% block extra_head %}{% endblock %}
  </head>
  <body>
    <div class="container">
      <div class="row">

        <div class="side_bar col">
          {% block side_bar %}
            {% if user.is_authenticated %}
              <p>{{ user.first_name }}</p>
              <p>Login: {{ user.username }}</p>

              <i class="fas fa-clipboard-list"></i>&nbsp;<a href="{% url "tasks:list" %}">задачи</a>
            {% endif %}
	    <i class="fas fa-cog"></i>&nbsp;<a href='{% url 'admin:index' %}'>админка</a>
          {% endblock %}
        </div>

        <div class="main_content col-8">
          {% block main_content %}
          {% endblock %}
        </div>

      </div>
    </div>
  </body>
</html>